#!/bin/sh

DAEMON=/srv/go/bin/revel
mode=prod
port=9090
package="github.com/dr013/carousel"
NAME="carousel"
desc="CI/CD service Carousel"
args="run ${package} ${mode} ${port}"
LOGFILE=/var/log/carousel.log
pidfile=/var/run/$name.pid

start() {
    echo -n "starting up $desc"
    RUN=`cd $GOPATH && $DAEMON $args > $LOGFILE 2>&1`

    if [ "$?" -eq 0 ]; then
        echo "Done."
    else
        echo "FAILED."
    fi
}

stop() {
    killall $DAEMON
}

status() {
    killall -0 $DAEMON

    if [ "$?" -eq 0 ]; then
        echo "Running."
    else
        echo "Not Running."
    fi
}

case "$1" in
    start)
    start
    ;;

    restart)
    stop
    sleep 2
    start
    ;;

    stop)
    stop
    ;;

    status)
    status
    ;;

    *)
    echo "usage : $0 start|restart|stop|status"
    ;;
esac

exit 0
